### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by redefault** [MicrocontrollersDev/OverlayTweaks#1]
- [x] Shield Opacity
- [x] Custom Shield Height
- [x] Remove Water Affecting FOV

**Comment by MicrocontrollersDev** [comment]
water affecting fov can be disabled in vanilla when FOV effects are set to 0% in accessibility settings, but it seems simple enough? hopefully just a WrapWithCondition? prolly will but if i dont then /shrug

**Comment by MicrocontrollersDev** [comment]
![2023-07-21_13 12 33](https://github.com/MicrocontrollersDev/OverlayTweaks/assets/66657148/58d97da7-5646-4412-8b7e-c71da6b95115)
current progress

**Comment by MicrocontrollersDev** [comment]
So bit of an issue. It seems like the first person shield overlay isn't a separate overlay, it's actually rendering the whole the same way it does in third person. This means if you decrease opacity or change the position, it'll change for everyone and in containers too, meaning shields could be half way between container slots. This makes it incredibly difficult to do any sort of modifying that doesn't break other things. Also seems like Mojang introduced some failsafe that forces the shield to render as opaque, as I can freely change the RGB values but changing the alpha in the same method does nothing. This was probably done to prevent https://bugs.mojang.com/browse/MC-165403. Will see what I can do about it but honestly not looking so hot right now. Mixces said he's looking into some things for his old animations mod so hopefully he'll be able to figure out more than me.

**Comment by MicrocontrollersDev** [comment]
Update: I got translucency working for held shields but it applies for other players as well. I am not planning on looking to fix this for now, maybe later when I understand mixins and the code better

**Comment by MicrocontrollersDev** [comment]
All three are now part of 1.1.0

Get it here: https://modrinth.com/mod/overlaytweaks/version/1.1.0
