### ISSUE TITLE
Game crashes when title with 0 length is displayed ( /title @s title "" )

### ISSUE THREAD

**Issue by Trexler180** [MicrocontrollersDev/OverlayTweaks#11]
Game crashes when a title with 0 length is displayed when the option "Automatically scale titles" is on,

to reproduce open world with cheats and scaling titles option enabled, 
tun command /title @s title ""

result: game should crash.
expected result: game should not crash.

**Comment by MicrocontrollersDev** [comment]
Should hopefully be fixed with 1.4.5 https://modrinth.com/mod/overlaytweaks/version/1.4.5

**Comment by Trexler180** [comment]
Works perfectly and makes the subtitle work as intended as well.
