### ISSUE TITLE
"Move Hotbar Up" option is gone in 1.20.4?

### ISSUE THREAD

**Issue by NiaSwift** [MicrocontrollersDev/OverlayTweaks#14]
# 1.20.2
![image](https://github.com/MicrocontrollersDev/OverlayTweaks/assets/95272690/6e0caf0a-df6b-4ece-be01-2afe00a5cc86)

# 1.20.4
![image](https://github.com/MicrocontrollersDev/OverlayTweaks/assets/95272690/4d4997ca-d680-44db-bafe-4d2dad3d8495)

**Comment by MicrocontrollersDev** [comment]
i removed it since [Raised](https://modrinth.com/mod/raised) has much better compatibility than my version
