### ISSUE TITLE
Esc button in ModMenu config throws warn about saving changes when it was saved

### ISSUE THREAD

**Issue by Dreig-Michihi** [MicrocontrollersDev/OverlayTweaks#17]
The same video, but with time code. First, I clicked [Save], then tapped Esc, but got the notification. I can get back from the menu only with [Cancel] button, ant it isn't obviously.
https://youtu.be/l1eFWQx82fY?t=16

**Comment by MicrocontrollersDev** [comment]
This is an issue with YACL. It should be fixed in this version https://modrinth.com/mod/yacl/version/3.3.2+1.20.4-fabric
