### ISSUE TITLE
add a function that removes hand shake.

### ISSUE THREAD

**Issue by Ebanytiy** [MicrocontrollersDev/OverlayTweaks#19]
Even when the "disable hand bobbing" function is enabled, the hands still move.
![2024-02-14_22 12 34](https://github.com/MicrocontrollersDev/OverlayTweaks/assets/87265332/a4dc700e-2e11-471e-98a6-d0a8a0110101)

https://github.com/MicrocontrollersDev/OverlayTweaks/assets/87265332/89f908e8-1435-4780-8f05-301fdf76d474

**Comment by MicrocontrollersDev** [comment]
good idea, will look into this when i get the time

**Comment by MicrocontrollersDev** [comment]
implemented as of version 1.7.1
