### ISSUE TITLE
Partially incompatible with Show Me Your Skin! (ModMenu only)

### ISSUE THREAD

**Issue by SplendidAlakey** [MicrocontrollersDev/OverlayTweaks#21]
**MC** 1.20.4
**FAPI** 0.96.4
**[Show Me Your Skin!](https://modrinth.com/mod/show-me-your-skin)** 1.8.0
**Overlay Tweaks** 1.7.2
**ModMenu** 9.0.0

When all 3 mods are installed together, entering Show Me Your Skin! config via ModMenu, while in the main menu, causes a crash. However, opening the same config menu in game does not, even if you open it via ModMenu. This is why I'm reporting it to you and not to SMYS, as I suspect Overlay Tweaks is expecting the player to exist in world, which is obviously not happening in the main menu, hence the crash.

Logs: 

- [Crash log](https://gist.github.com/SplendidAlakey/e8fb23c3d614cb60d52e6e8adedf47dd#file-crash-log)
- [Latest log](https://gist.github.com/SplendidAlakey/e8fb23c3d614cb60d52e6e8adedf47dd#file-latest-log)

**Comment by MicrocontrollersDev** [comment]
Yep, this is my fault. Don’t know why my mod causes an NPE and SMYS doesn’t here but should be an easy fix. Thank you for reporting will fix soon.

**Comment by MicrocontrollersDev** [comment]
While testing noticed that shield opacity is broken. Made a [new issue](https://github.com/MicrocontrollersDev/OverlayTweaks/issues/22) for this and I'll fix it some other time. This should be fixed in 1.7.3. Please reopen if I missed something
