### ISSUE TITLE
Crash When Riding (Some) Entities

### ISSUE THREAD

**Issue by Pie-Not-Lie** [MicrocontrollersDev/OverlayTweaks#25]
Game crashes when riding certain entities, seems to be living mobs only (something to do with the saddle-hearts, I assume??). Tested with Strider, Llama, Trader Llama, and Boat; Crashed with all but Boat.

**Comment by MicrocontrollersDev** [comment]
One of the features is ridden mount opacity, which is my guess. I'll look into it when I get the chance, I assume this is 1.21?

**Comment by Pie-Not-Lie** [comment]
Ahh. Yep, sorry! Meant to specify: Tested in 1.21 with just Fabric API, Mod Menu, and YACL. Thanks! :)

**Comment by MicrocontrollersDev** [comment]
This should be fixed with 1.9.3, please test it and let me know: https://modrinth.com/mod/overlaytweaks/version/1.9.3

**Comment by Pie-Not-Lie** [comment]
Seems to work great, thanks! :D
