### ISSUE TITLE
Crash in ModMenu with Show Me Your Skin!

### ISSUE THREAD

**Issue by SplendidAlakey** [MicrocontrollersDev/OverlayTweaks#26]
**MC** 1.21
**FAPI** 0.100.4
**[Show Me Your Skin!](https://modrinth.com/mod/show-me-your-skin)** 1.11.1
**Overlay Tweaks** 1.9.3
**ModMenu** 11.0.1

To reproduce install all of the above mods and open Show Me Your Skin! config in ModMenu.

Not sure if it's a repeat of #21 this time because the stack trace is different, so let me know if this will have to be fixed on SMYS' side, instead.

Latest log: https://gist.github.com/SplendidAlakey/8dc24159aedfa629ef6bed38aa60c425#file-latest-log
Crash log: https://gist.github.com/SplendidAlakey/8dc24159aedfa629ef6bed38aa60c425#file-crash-log

**Comment by MicrocontrollersDev** [comment]
this seems like a repeat of 21 because i at some point just simply removed the null check i used to fix it the first time? not sure what im doing im kinda stupid i guess. 

fixed in 1.9.4

**Comment by SplendidAlakey** [comment]
Haha, no worries, thanks for another swift fix!
