### ISSUE TITLE
`cancelDebugCrosshair` crash

### ISSUE THREAD

**Issue by Scarlaid** [MicrocontrollersDev/OverlayTweaks#4]
This is the crash log: https://mclo.gs/fh0ZFyf
This occurs on OverlayTweaks 1.3.0 on 1.20.1

**Comment by Scarlaid** [comment]
damn you're right, so this is ELS side fault then 👍

**Comment by Scarlaid** [comment]
Found the issue, it was not entirely ELS, BetterF3 has a debug crosshair that somehow incompatible with OverlayTweaks one

**Comment by Ownwn** [comment]
I'm also having this issue with BetterF3, did you ever find a workaround?

**Comment by MicrocontrollersDev** [comment]
haven't had time recently to do much of anything, give me a few days, a new non-ELS log would be helpful though

**Comment by Ownwn** [comment]
Yup here you go: [https://hst.sh/uxejogopok](url)

**Comment by MicrocontrollersDev** [comment]
okay well i stopped the crash but im not sure the best way to make the two mods fully compatible. if you want to disable the debug crosshair you'll have to disable them in both mods. just gonna keep it this way for now

**Comment by MicrocontrollersDev** [comment]
https://modrinth.com/mod/overlaytweaks/version/1.3.2
