### ISSUE TITLE
1.20 backport

### ISSUE THREAD

**Issue by Chief0609** [MicrocontrollersDev/OverlayTweaks#5]
I know that the mod says it works for 1.20, but it says that it only works for 1.20.1 and 1.21, would it be possible to make an update for 1.20 with all of the current features?

**Comment by MicrocontrollersDev** [comment]
Seems like fabric is incorrectly parsing the version thing in fabric.mod.json? Unless I'm just misunderstanding how it works. I'll fix it in the next release but for now you can just open the jar file using either 7zip or winrar, open the fabric.mod.json, and change the "minecraft" : "~1.20.1" to say "1.20" instead and it will just work. Remember to control+s to save and then 7zip or winrar will ask you if you want to save the archive.

**Comment by MicrocontrollersDev** [comment]
fixed in 1.3.2 https://modrinth.com/mod/overlaytweaks/version/1.3.2
