### ISSUE TITLE
Incompatibility with BetterF3

### ISSUE THREAD

**Issue by SkyWors** [MicrocontrollersDev/OverlayTweaks#6]
Hey!

OverlayTweaks is incompatible with [BetterF3](https://github.com/TreyRuffy/BetterF3).
The game crashes even before starting the window.

**Comment by MicrocontrollersDev** [comment]
Was this not fixed with 1.3.2? Can you send a crashlog since I no longer crash with them

**Comment by SkyWors** [comment]
The mode was deactivated on my instance, so I didn't get the last update, which solved the problem.
Sorry for the inconvenience!

**Comment by MicrocontrollersDev** [comment]
all good
